GPX-567: Actions starten jeden Montag um 07:00
gepaplexx/ansible-role-nginx pull request #2
Opened 2023-01-10 14:22 UTC by sgartner03

GPX-567: Actions werden jeden Montag um 07:00 ausgeführt

2023-01-10 14:23 UTC, Lucostus approved these changes
LGTM

2023-01-12 08:35 UTC, gattma requested changes

2023-01-12 08:35 UTC, gattma commented on .github/workflows/2-pull-request.yml
> +    - cron: "0 7 * * 1"
Hier wieder entfernen.

2023-01-18 09:01 UTC, merged

2023-01-18 09:06 UTC, sgartner03 commented
sorry marko, hab hier übersehen, dass ich den review hier gar nicht re-requested habe..